#SPDX-License-Identifier: MIT-0
---
# tasks file for install-deps
- name: Install curl, unzip, apt-transport-https
  apt:
    name: ['curl', 'apt-transport-https', 'unzip']
    state: present
    update_cache: yes

- name: Install Helm
  shell: |
    curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm

- name: Install system packages
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop:
    - python3
    - python3-pip

- name: Install Python hvac package
  pip:
    name: hvac
    executable: pip3

# - name: Install kubectl
#   shell: |
#     curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
#     install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
#   args:
#     creates: /usr/local/bin/kubectl
