# SPDX-License-Identifier: MIT-0
---
# roles/kube/tasks/fetch_kubeconfig.yml
- name: Check if kubeconfig exists on master node
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: kubeconfig_stat
  become: true

- name: Fail if kubeconfig doesn't exist on master
  ansible.builtin.fail:
    msg: "Kubeconfig file /etc/kubernetes/admin.conf does not exist on master node"
  when: not kubeconfig_stat.stat.exists

- name: Create local .kube directory
  local_action:
    module: file
    path: "{{ lookup('env', 'HOME') }}/.kube"
    state: directory
    mode: '0755'
  become: false

- name: Check if local kubeconfig exists
  local_action:
    module: stat
    path: "{{ lookup('env', 'HOME') }}/.kube/config"
  register: local_kubeconfig_stat
  become: false

- name: Backup existing kubeconfig if it exists
  local_action:
    module: copy
    src: "{{ lookup('env', 'HOME') }}/.kube/config"
    dest: "{{ lookup('env', 'HOME') }}/.kube/config.backup.{{ ansible_date_time.epoch }}"
    remote_src: true
  when: local_kubeconfig_stat.stat.exists
  become: false

- name: Fetch kubeconfig from master node
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: "{{ lookup('env', 'HOME') }}/.kube/config"
    flat: yes
    fail_on_missing: yes
  become: true

- name: Set kubeconfig permissions
  local_action:
    module: file
    path: "{{ lookup('env', 'HOME') }}/.kube/config"
    mode: '0600'
  become: false

- name: Test kubectl connectivity
  local_action:
    module: shell
    cmd: kubectl cluster-info
  register: cluster_test
  environment:
    KUBECONFIG: "{{ lookup('env', 'HOME') }}/.kube/config"
  ignore_errors: true
  become: false

- name: Display success message
  ansible.builtin.debug:
    msg: "✅ Kubeconfig successfully fetched and kubectl can connect to cluster"
  when: cluster_test.rc == 0

- name: Display cluster connection info
  ansible.builtin.debug:
    msg: "{{ cluster_test.stdout }}"
  when: cluster_test.rc == 0

- name: Display warning if connection fails
  ansible.builtin.debug:
    msg: "⚠️ Kubeconfig fetched but kubectl cannot connect. Check network connectivity and firewall settings."
  when: cluster_test.rc != 0