# SPDX-License-Identifier: MIT-0
---
# handlers file for kubernetes master/worker

- name: restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: true
  listen: restart docker

- name: restart cri-dockerd
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    daemon_reload: yes
    enabled: yes
  loop:
    - cri-docker.socket
    - cri-docker.service
  become: true
  listen: restart cri-dockerd