#SPDX-License-Identifier: MIT-0
---
# tasks file for k8s-deploy
- name: Install pip3
  apt:
    name: python3-pip
    state: present
    update_cache: true

- name: Install kubernetes Python client
  pip:
    name: kubernetes
    executable: pip3

# - name: Deploy postgres
#   kubernetes.core.k8s:
#     definition: "{{ lookup('template', 'postgres-deployment.yaml.j2') }}"
#     state: present
#     namespace: default 
#   environment:
#     KUBECONFIG: /etc/kubernetes/admin.conf

# - name: Deploy postgres service
#   kubernetes.core.k8s:
#     definition: "{{ lookup('template', 'postgres-service.yaml.j2') }}"
#     state: present
#     namespace: default 
#   environment:
#     KUBECONFIG: /etc/kubernetes/admin.conf

- name: Deploy backend
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'backend-deployment.yaml.j2') }}"
    state: present
    namespace: default 
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Deploy backend service
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'backend-service.yaml.j2') }}"
    state: present
    namespace: default 
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Deploy frontend
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'frontend-deployment.yaml.j2') }}"
    state: present
    namespace: default 
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Deploy frontend service
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'frontend-service.yaml.j2') }}"
    state: present
    namespace: default 
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

# - name: Deploy ingress nginx
#   kubernetes.core.k8s:
#     definition: "{{ lookup('template', 'frontend-ingress.yaml.j2') }}"
#     state: present
#     namespace: default
#   environment:
#     KUBECONFIG: /etc/kubernetes/admin.conf