# SPDX-License-Identifier: MIT-0
---
# Join node to Kubernetes cluster

- name: Get join command from master
  ansible.builtin.slurp:
    src: /tmp/kubernetes-join-command
  register: join_command_b64
  delegate_to: "{{ groups['master'][0] }}"

- name: Decode join command
  ansible.builtin.set_fact:
    join_command: "{{ join_command_b64.content | b64decode | trim }}"

- name: Display join command
  ansible.builtin.debug:
    msg: "Join command: {{ join_command }}"

- name: Join worker node to cluster
  ansible.builtin.shell: "{{ join_command }}"
  register: join_result
  become: true
  failed_when: join_result.rc != 0 and "already exists" not in join_result.stderr

- name: Display join result
  ansible.builtin.debug:
    msg: "{{ join_result.stdout }}"
