# SPDX-License-Identifier: MIT-0
---
# Ensure required kernel modules and cri-dockerd are available

- name: Load kernel modules and enable sysctl
  shell: |
    modprobe br_netfilter
    echo 'br_netfilter' >> /etc/modules-load.d/k8s.conf
    echo 'net.bridge.bridge-nf-call-iptables = 1' >> /etc/sysctl.d/k8s.conf
    echo 'net.ipv4.ip_forward = 1' >> /etc/sysctl.d/k8s.conf
    sysctl --system
  become: true

- name: Install cri-dockerd dependencies
  apt:
    name:
      - git
      - wget
      - curl
      - make
      - gcc
      - golang
    update_cache: yes
    state: present
  become: true

- name: Clone cri-dockerd repo
  git:
    repo: https://github.com/Mirantis/cri-dockerd.git
    dest: /opt/cri-dockerd
    version: master
  become: true


# added new

- name: Remove any default golang installation
  apt:
    name: golang
    state: absent
  become: true

- name: Download Go 1.21.10 tarball
  get_url:
    url: https://go.dev/dl/go1.21.10.linux-amd64.tar.gz
    dest: /tmp/go1.21.10.linux-amd64.tar.gz
    mode: '0644'

- name: Remove old Go directory
  file:
    path: /usr/local/go
    state: absent
  become: true

- name: Extract Go
  unarchive:
    src: /tmp/go1.21.10.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes
  become: true

- name: Add Go to PATH
  ansible.builtin.shell: |
    echo 'export PATH=$PATH:/usr/local/go/bin' >> /etc/profile.d/go.sh
    chmod +x /etc/profile.d/go.sh
  become: true

- name: Load Go PATH for current shell
  ansible.builtin.shell: source /etc/profile.d/go.sh
  args:
    executable: /bin/bash


# end 
- name: Build cri-dockerd binary
  shell: |
    cd /opt/cri-dockerd
    mkdir -p bin
    go build -o bin/cri-dockerd
  args:
    creates: /opt/cri-dockerd/bin/cri-dockerd
  become: true

- name: Move cri-dockerd binary to /usr/bin
  copy:
    src: /opt/cri-dockerd/bin/cri-dockerd
    dest: /usr/bin/cri-dockerd
    mode: '0755'
  become: true

- name: Copy cri-dockerd service file
  copy:
    src: /opt/cri-dockerd/packaging/systemd/cri-dockerd.service
    dest: /etc/systemd/system/cri-dockerd.service
  become: true

- name: Enable and start cri-dockerd
  systemd:
    name: cri-dockerd
    enabled: true
    state: started
    daemon_reload: true
  become: true
