---
- name: Common setup
  hosts: all
  become: yes
  roles:
    - my-roles/common

- name: Master setup
  hosts: master
  become: yes
  roles:
    - my-roles/master

- name: Slave setup
  hosts: slaves
  become: yes
  roles:
    - my-roles/slaves

